version: '3.8'
services:
  backend:
#    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  queue:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    command: "python products/consumer.py"
    depends_on:
      - db

  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    command: --port=3306